
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8002
          predicates:
            - Path=/api/**
      default-filters:
        - AddRequestHeader=username,ranxu

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
server:
  port: 8012

dubbo:
  application:
    name: dubbo-springboot-demo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848


